Geet/Project/Geet/Geet/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from .import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'admin/', admin.site.urls),
    url(r'^$', views.HomePage.as_view(), name="home"),
    url(r'accounts/', include("accounts.urls", namespace="accounts")),
    url(r'accounts/', include('django.contrib.auth.urls')),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Geet/Project/Geet/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    url('register/', views.registration, name="signup"),
    url('login/', views.loginUser, name="login"),
    url('logout/', views.logoutUser, name="logout"),
    url('upload/', views.upload, name="upload"),
    url('startlistening/player/<int:id>/', views.player, name="player"),
    url('startlistening/', views.startlistening, name="startlistening"),
    url('channel/',views.channel,name="channel"),
    url('', views.index, name="home"),
    
]


Geet/Project/Geet/accounts/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Song(models.Model):
    song_id=models.AutoField(primary_key=True)
    song_name=models.CharField(max_length=1000)
    singer_name=models.CharField(max_length=1000)
    image=models.ImageField(upload_to='documents/')
    song_genre = models.CharField(max_length=1000, default="")
    song = models.FileField(upload_to='documents/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.song_name

class Watchlater(models.Model):
    watch_id=models. AutoField (primary_key=True)
    user = models.ForeignKey(User, on_delete= models.CASCADE)
    video_id = models. CharField(max_length=10000000, default="")


class History(models.Model):
    history_id =models. AutoField (primary_key=True)
    user = models.ForeignKey(User, on_delete= models.CASCADE)
    music_id = models. CharField(max_length=10000000, default="")

Geet/Project/Geet/accounts/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class CreateUser(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]





Geet/Project/Geet/Geet/views.py
from django.views.generic import TemplateView


class HomePage(TemplateView):
    template_name = "index.html"


Geet/Project/Geet/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib import messages, auth
from django.http import HttpResponse
from django.forms import inlineformset_factory
from django.contrib.auth.forms import UserCreationForm
from .forms import CreateUser
from django.contrib.auth import authenticate, login, logout
from .models import *
from django.contrib.auth.decorators import login_required

# Create your views here.

@login_required(login_url='/accounts/login/')
def index(request):
    song = Song.objects.all()
    return render(request, 'index.html', {'song':song})

def watchlater(request):
    
    return render(request, 'accounts/watchlater.html')

def upload(request):
        if request.method=="POST":
            song_name=request.POST["Song name"]
            singer_name=request.POST["Singer"]
            genre = request.POST["Genre"]
            songs = request.FILES["InputFile"]
            image= request.FILES["InputImage"]
            song_model = Song(song_name=song_name, singer_name=singer_name, song_genre=genre, image=image, song=songs)
            song_model.save()
        return render(request, 'accounts/upload.html')

def startlistening(request):
    song = Song.objects.all()
    return render(request, 'accounts/startlistening.html',{'song':song})

def player(request, id):
    song = Song.objects.filter(song_id = id).first()
    return render(request, 'accounts/player.html',{'song':song})

def registration(request):
    if request.user.is_authenticated:
        return redirect('home')
    else:
        form = CreateUser()
        if request.method == 'POST':
            form = CreateUser(request.POST)
            if form.is_valid():
                form.save()
                user = form.cleaned_data.get('username')
                messages.success(request, 'Account was created for ' + user)

                return redirect('login')

        context = {'form': form}
        return render(request, 'accounts/signup.html', context)


def loginUser(request):
    if request.user.is_authenticated:
        return redirect('home')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('home')
            else:
                messages.info(request, 'Username OR password is incorrect')

        context = {}
        return render(request, 'accounts/login.html', context)


def logoutUser(request):
    logout(request)
    return redirect('login')

def channel(request, channel):
        

    return render(request, "accounts/channel.html")
        



Geet/Project/Geet/accounts/templates/accounts/base.html
<!DOCTYPE html>
{% load static %}

<html>
    <head>
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <title>Geet</title>
        <link rel="stylesheet" href="{% static 'Geet/base.css' %}"> 
       <link rel="stylesheet" href="{% static 'Geet/styles.css' %}"> 
       <link rel="stylesheet" href="{% static 'Geet/startlistening.css' %}"> 
       <link rel="stylesheet" href="{% static 'Geet/upload.css' %}"> 
       <link rel="stylesheet" href="{% static 'Geet/player.css' %}"> 
    </head>
    
    <body>
        
        <div class="navbar">
                <img src = "{% static 'Geet/logo2.png' %}" class = "logo">
                <ul>
                    <li><a href="{% url 'home' %}">Home</a></li>
                    <li><a href="/accounts/startlistening/">Start Listening</a></li>
                    <li><a href="{% url 'accounts:upload' %}">Upload</a></li>
                    <li><a href="#">Community</a></li>
                    {% if not user.is_authenticated %}
                    <li class = "dropdown"><button class="dropbtn">Connect</button>
                        <div class = "dropdown-content">
                            <a href="{% url 'accounts:login'%}">Log In</a>
                            <a href="{% url 'accounts:signup'%}">Sign Up</a>
  
                    </li> 
                    {% endif %}
                <li class = "dropdown1">
                    {% if user.is_authenticated %}
                    {% comment %} <img src = "{% static 'Geet/Profile.png' %}" class = "Userimage"> {% endcomment %}
                    <button onclick="myFunction()" class="dropbtn1">Hello, {{request.user}}</button>
                    <div id="myDropdown" class = "dropdown-content1">
                          <a  class="logout" href="{% url 'logout' %}">Logout</a>
                          <a class="channel" href="{% url 'accounts:channel' %}">Your Channel</a>

                    </div>

                    {% endif %}


                </li>
                </ul>
            </div>
 {% block content %}

 {% endblock %}
           
    <script>
            /* When the user clicks on the button, 
            toggle between hiding and showing the dropdown content */
            function myFunction() {
            document.getElementById("myDropdown").classList.toggle("show");
            }

            // Close the dropdown if the user clicks outside of it
            window.onclick = function(event) {
            if (!event.target.matches('.dropbtn1')) {
                var dropdowns = document.getElementsByClassName("dropdown-content1");
                var i;
                for (i = 0; i < dropdowns.length; i++) {
                var openDropdown = dropdowns[i];
                if (openDropdown.classList.contains('show')) {
                    openDropdown.classList.remove('show');
                }
                }
            }
            }
    </script>
</html>

Geet/Project/Geet/accounts/templates/accounts/listenlater.html
{% extends "accounts/base.html" %}

{%  block content %}

  <body>
     <div class="container">
            <div class="heading">Listen Later</div>
                
            <div class="music-container">
                {% if song|length < 1 %}
                  <h1>Listen Later is Empty.</h1>
                  {% endif %}

        {% for i in song reversed %}
            <div class="box">
                <div class="image">
                    <img src="{{i.image.url}}">
                </div>
                <div class="name">
                    {{i.singer_name}} - {{i.song_name}}
                </div>
                <div class="music">
                 <audio controls>
                 <source src="{{i.song.url}}" type="audio/mpeg">
                 </audio>
                 <div class="row">
                       
                    <a href="/accounts/startlistening/{{i.song_id}}"><button class="btn btn-primary"style="margin-left: 2%;" >Listen Song</button></a>
                
               </div>
                </div>
            </div>
        {% endfor %}

            </div>
        </div>
        <script>
            /* When the user clicks on the button, 
            toggle between hiding and showing the dropdown content */
            function myFunction() {
            document.getElementById("myDropdown").classList.toggle("show");
            }

            // Close the dropdown if the user clicks outside of it
            window.onclick = function(event) {
            if (!event.target.matches('.dropbtn1')) {
                var dropdowns = document.getElementsByClassName("dropdown-content1");
                var i;
                for (i = 0; i < dropdowns.length; i++) {
                var openDropdown = dropdowns[i];
                if (openDropdown.classList.contains('show')) {
                    openDropdown.classList.remove('show');
                }
                }
            }
            }
    </script>

  {% endblock %}

Geet/Project/Geet/accounts/templates/accounts/login.html
<!DOCTYPE html>
<html>

<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: rgba(178,219,213, 0.3) !important;
			font-family: 'Poppins', sans-serif;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #fff;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			font-size: 25px;
            font-weight:500;
			color: #40978a;
		}

		.login_btn {
			width: 100%;
			background: #1e9b88 !important;
			color: white !important;
		}

		.login_btn:hover{
			background:#5ebdae;
		}

		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #42958e !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>
</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>

							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>

						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>

								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>

				{% for message in messages %}
					<p id="messages">{{message}}</p>
				{% endfor %}

				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'accounts:signup' %}" class="ml-2">Sign Up</a>
					</div>

				</div>
			</div>
		</div>
	</div>
</body>

</html>

Geet/Project/Geet/accounts/templates/accounts/player.html
{% extends 'accounts/base.html' %}
{% block content %}
{% load static %}

<div class="whole">
  <div class="main">
  	<p id="logo"><i class="fa fa-music"></i>Music</p>
 
     <div class="left">

      <img id="track_image" src = "{{song.image.url}}">
         <div class="volume">
            <p id="volume_show">90</p>
            <i class="fa fa-volume-up" aria-hidden="true" onclick="mute_sound()" id="volume_icon"></i>
            <input type="range" min="0" max="100" value="90" onchange="volume_change()" id="volume">  
         </div>

     </div>
 

  	 <div class="right">

        <!-- <div class="show_song_no">
          <p id="present">1</p>
          <p>/</p>
          <p id="total">5</p>
        </div> -->

      <p id="title">{{song.song_name}}</p>
      <p id="artist">{{song.singer_name}}</p>

  	 	<div class="middle">
  	       <button onclick="previous_song()" id="pre"><i class="fa fa-step-backward" aria-hidden="true"></i></button>
      	   <button onclick="justplay()" id="play"><i class="fa fa-play" aria-hidden="true"></i></button>
  	       <button onclick="next_song()" id="next"><i class="fa fa-step-forward" aria-hidden="true"></i></button>
  	   </div>


        <div class="duration">
           <input type="range" min="0" max="100" value="0" id="duration_slider" onchange="change_duration()">
        </div>
           <button id="auto" onclick="autoplay_switch()">Auto play <i class="fa fa-circle-o-notch" aria-hidden="true"></i></button>
  	</div>


  </div>
</div>   
  
{% endblock %}
<script src="{% static 'Geet/player.js' %}"></script>

Geet/Project/Geet/accounts/templates/accounts/startlistening.html
{% extends "accounts/base.html" %}

{%  block content %}

  <body>
     <div class="container">
            <div class="heading">Start Listening</div>
                
            <div class="music-container">

        {% for i in song reversed %}
            <div class="box">
            
                <div class="image">
                    <a href="/accounts/startlistening/player/{{i.song_id}}">
                    <img src="{{i.image.url}}">
                </a>
                </div>
                <div class="name">
                    {{i.singer_name}} - {{i.song_name}}
                </div>
                
                <div class="music">
                 <audio controls>
                 <source src="{{i.song.url}}" type="audio/mpeg">
                 </audio>
                 <!-- <a href="accounts/startlistening/{{i.song_id}}"><button>Listen Song</button></a> -->
                </div>
            </div>
        {% endfor %}

            </div>
        </div>
        <script>
            function myFunction() {
            document.getElementById("myDropdown").classList.toggle("show");
            }

            window.onclick = function(event) {
            if (!event.target.matches('.dropbtn1')) {
                var dropdowns = document.getElementsByClassName("dropdown-content1");
                var i;
                for (i = 0; i < dropdowns.length; i++) {
                var openDropdown = dropdowns[i];
                if (openDropdown.classList.contains('show')) {
                    openDropdown.classList.remove('show');
                }
                }
            }
            }
    </script>

  {% endblock %}

Geet/Project/Geet/accounts/templates/accounts/test.html
{% extends "accounts/base.html" %}

{%  block content %}

  <div> Hello </div>

  {% endblock %}

Geet/Project/Geet/accounts/templates/accounts/watchlater.html
<!DOCTYPE html>


<html>
    <head>
    

        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width", intital-scale="1.0">
        <title>Start Listening</title>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200&display=swap" rel="stylesheet">
    
    
        <style>
            *{
                margin:0;
                padding: 0;
                font-family: 'Poppins', sans-serif;
                
            }
                  
            .container .heading{
                font-size: 40px;
                font-weight: 1000;
                padding:30px 0;
                text-align: center;
                font-family: 'Poppins', sans-serif;
                color: #40978a;
            }
            
            .container .music-container{
                display:flex;
                align-items: center;
                flex-flow: column;
            }
            
            .container .music-container .box{
                height: 230px;
                width: 80%;
                display: flex;
                align-items: center;
                background: #f2f3f5;
                border-radius: 5px;
                box-shadow: 0 2px 4px #000;
                overflow: hidden;
                margin: 20px;
            }
                  
            .container .music-container .box .image{
                height: 100%;
                width: 25%;
            }
            
            .container .music-container .box .image img{
                height: 100%;
                width: 100%;
                object-fit: cover;
            }
            
            .container .music-container .box .music{
                width: 55%;
                position: absolute;
                padding-left: 300px;
            }
            
            .container .music-container .box .music audio{
                width: 100%;
                outline: none;
            }
            
            .container .music-container .box .music audio::-webkit-media-controls-eclosure{
                background: none;
            }
    
            .container{
                height:100vh;
                width:100%;
                background-size: cover;
                background-position: center;
                position: relative;
            }
    
            .navbar{
                width: 100%;
                background: linear-gradient(to left,#89c3bb, #94b8be );
                margin: auto;
                padding: 15px 0px;
                display: flex;
                align-items: center;
                justify-content: space-between;
            }
    
            .dropbtn {
                background-color: #1e9b88;
                border-radius: 10px;
                color: white;
                padding: 10px;
                font-size: 15px;
                border: none;
            }
    
            .dropdown-content {
                display: none;
                position: fixed;
                border-radius: 10px;
                background-color: rgb(101, 171, 192);
                box-shadow: 0px 6px 14px 0px rgba(0,0,0,0.2);
                z-index: 1;
            }
    
            .dropdown {
                position: relative;
                display: inline-block;
            }
    
            .dropdown-content a {
                color: black;
                text-decoration: none;
                display: block;
                font-size: 12px;
                min-width: 60px;
            }
    
            .dropdown-content a:hover {background-color: rgb(49, 121, 109);}
    
            .dropdown:hover .dropdown-content {display: block;}
    
            .dropdown:hover .dropbtn {background-color: #5a92c5;}
    
            .logo{
                width:80px;
                padding-left: 15px;
            }
    
            .navbar ul li{
                list-style: none;
                display: inline-block;
                margin: 0 15px;
            }
    
            .navbar ul li a{
                text-decoration: none;
                color:#fff;
                font-size: 5 px;
                text-transform: uppercase;
                transition: all ease 0.5s;
                padding: 2vh;
                border-radius: 10px;
                letter-spacing: 1;
                font-weight: 1000;
            }
    
            .navbar ul li :hover{
                background-color:rgba(58, 148, 160, 0.6);
            }
    
            .content{
                width: 100%;
                position: absolute;
                top: 30%;
            }
    
            .dropbtn1 {
        background-color: #1e9b88;
        border-radius: 10px;
        color: white;
        padding: 10px;
        font-size: 15px;
        border: none;
        cursor: pointer;
         }
    
         .dropbtn1:hover, .dropbtn1:focus {
            background-color: #5a92c5;;
         }
    
         .dropdown1 {
         position: relative;
         display: inline-block;
         }
    
         .dropdown-content1 {
         display: none;
         position: absolute;
         background-color: rgb(101, 171, 192);;
         min-width: 110px;
         border-radius:5px;
         overflow: auto;
         box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
         z-index: 1;
         }
    
         .dropdown-content1 a {
         color: black;
         font-size:12px;
         padding: 12px 16px;
         text-decoration: none;
         display: block;
         }
    
         .dropdown1 a:hover {background-color: rgb(49, 121, 109);}
    
                .show {display: block;}
    
                .container1{
                    height:100vh;
                    width:100%;
                    background-size: cover;
                    background-position: center;
                    position: relative;
                }
    
                .name{
                    font-size: 22px;
                    color: #273d3a;
                    padding-left: 10px;
                    position: relative;
                    bottom: 95px;
                    font-weight:900;
                }
            
        </style>
    
    
    




    </head>
  <body>
      {%load static%}
    <div class="navbar">
        <img src = "{% static 'Geet/logo2.png' %}" class = "logo">
        <ul>
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="#">Start Listening</a></li>
            <li><a href="{% url 'accounts:upload' %}">Upload</a></li>
            <li><a href="#">Community</a></li>
            {% if not user.is_authenticated %}
            <li class = "dropdown"><button class="dropbtn">Connect</button>
                <div class = "dropdown-content">
                    <a href="{% url 'accounts:login'%}">Log In</a>
                    <a href="{% url 'accounts:signup'%}">Sign Up</a>

                
            </li> 
            {% endif %}
        <li class = "dropdown1">
            {% if user.is_authenticated %}
            {% comment %} <img src = "{% static 'Geet/Profile.png' %}" class = "Userimage"> {% endcomment %}
            <button onclick="myFunction()" class="dropbtn1">Hello, {{request.user}}</button>
            <div id="myDropdown" class = "dropdown-content1">
                  <a  class="logout" href="{% url 'logout' %}">Logout</a>
                  <a class="channel" href="{% url 'accounts:channel' %}">Your Channel</a>
            </div>

            {% endif %}


        </li>
        </ul> 
    </div>
  </body>

</html>

Geet/Project/Geet/templates/index.html
<!DOCTYPE html>
{% load static %}

<html>
    <head>
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200&display=swap" rel="stylesheet">
        <title>Geet</title>
       <link rel="stylesheet" href="{% static 'Geet/styles.css' %}">    
    </head>
    <body>
        
    <div class="container">
        <div class="navbar">
                <img src = "{% static 'Geet/logo2.png' %}" class = "logo">
                <ul>
                    <li><a href="{% url 'home' %}">Home</a></li>
                    <li><a href="{% url 'accounts:startlistening' %}">Start Listening</a></li>
                    <li><a href="{% url 'accounts:upload' %}">Upload</a></li>
                    <li><a href="#">Community</a></li>
                    {% if not user.is_authenticated %}
                    <li class = "dropdown"><button class="dropbtn">Connect</button>
                        <div class = "dropdown-content">
                            <a href="{% url 'accounts:login'%}">Log In</a>
                            <a href="{% url 'accounts:signup'%}">Sign Up</a>

                        
                    </li> 
                    {% endif %}
                <li class = "dropdown1">
                    {% if user.is_authenticated %}
                    {% comment %} <img src = "{% static 'Geet/Profile.png' %}" class = "Userimage"> {% endcomment %}
                    <button onclick="myFunction()" class="dropbtn1">Hello, {{request.user}}</button>
                    <div id="myDropdown" class = "dropdown-content1">
                          <a  class="logout" href="{% url 'logout' %}">Logout</a>
                          <a class="channel" href="{% url 'accounts:channel' %}">Your Channel</a>

                    </div>

                    {% endif %}


                </li>
                </ul>
            </div>

                <div class = "content">
                    <div class="left-col">
                    <h1>GEET <br> FOR <br> BEAT</h1>
                    </div>
                </div>
            </div>

        <div class="footer-container">
            <div class="footer">
                <div class="footer-heading footer-1">
                    <h2>About Us</h2>
                    <a href="#">Our Story</a>
                    <a href="#">FAQs</a>
                    <a href="#">Team</a>
                    <a href="#">Privacy Policy</a>
                    <a href="#">Terms of Service</a>
                </div>
                <div class="footer-heading footer-2">
                    <h2>Contact Us</h2>
                    <a href="#">Jobs</a>
                    <a href="#">Support</a>
                    <a href="#">Help Center</a>
                    <a href="#">Vendors</a>
                </div>
                <div class="footer-heading footer-3">
                    <h2>Useful Links</h2>
                    <a href="#">For Artists</a>
                    <a href="#">Blog</a>
                    <a href="#">Something</a>
                    <a href="#">Another thing</a>
                </div>
                <div class="footer-heading footer-4">
                    <h2>Follow Us</h2>
                    <a href="#">Facebook</a>
                    <a href="#">Instagram</a>
                    <a href="#">Twitter</a>
                    <a href="#">LinkedIn</a>
                </div>
                <div class="footer-email-form">
                    <h2>Join our newsletter</h2>
                    <input type="email" placeholder = "Enter your email" id="footer-email">
                    <button id = "footer-email-button">Sign Up</button>
                </div>
            </div>
        </div>

    <script>
            /* When the user clicks on the button, 
            toggle between hiding and showing the dropdown content */
            function myFunction() {
            document.getElementById("myDropdown").classList.toggle("show");
            }

            // Close the dropdown if the user clicks outside of it
            window.onclick = function(event) {
            if (!event.target.matches('.dropbtn1')) {
                var dropdowns = document.getElementsByClassName("dropdown-content1");
                var i;
                for (i = 0; i < dropdowns.length; i++) {
                var openDropdown = dropdowns[i];
                if (openDropdown.classList.contains('show')) {
                    openDropdown.classList.remove('show');
                }
                }
            }
            }
    </script>
    </body>
</html>